-- Look and feel (omarchy-ubuntu kit). Omarchy values apply (gaps 5/10, border 2, square corners,
-- no blur or shadow, dwindle). Uncomment to adjust.

-- hl.config({
--   decoration = {
--     rounding = 8,               -- rounded corners (your previous config)
--   },
--   general = {
--     gaps_in = 4, gaps_out = 8,  -- your previous gaps
--     -- layout = "scrolling",    -- niri-like layout
--   },
-- })
